---

- name: Create storage directory on host
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0700
    owner: "{{ docker_sinopia_uid }}"
  with_items:
    - "{{ docker_sinopia_host_path }}/storage"
    - "{{ docker_sinopia_host_path }}/conf"

- name: Set up config
  template:
    src: "config.yaml.j2"
    dest: "{{ docker_sinopia_host_path }}/conf/config.yaml"
    mode: 0600
    owner: "{{ docker_sinopia_uid }}"
  notify: restart-sinopia

- name: Generate htpasswd
  htpasswd:
    path: "{{ docker_sinopia_host_path }}/conf/htpasswd"
    mode: 0600
    owner: 100
    crypt_scheme: des_crypt
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ docker_sinopia_users }}"
  when: docker_sinopia_users
  notify: restart-sinopia

- name: Install container
  docker_container:
    name: "{{ docker_sinopia_container_name }}"
    image: "{{ docker_sinopia_image }}"
    state: "started"
    restart_policy: 'always'
    volumes:
      - "{{ docker_sinopia_host_path }}:/verdaccio"
    ports:
      - "{{ docker_sinopia_port }}:4873"
